---
title: "Clase2"
author: "Julian Avila-Jimenez"
date: "18/8/2020"
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, cache = T, warning = F)
library(tidyverse)
library(knitr)
library(kableExtra)
```

## Extint plants 

[TidyTuesday data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-08-18/readme.md) from the **IUCN** [Red List of Trheatened Species](https://www.iucnredlist.org/) 

```{r Carga de datos}
plants <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv")

actions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv")

threats <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv")

```

## Datos de Sudamerica
```{r}
SouthAmP<-plants %>% 
  filter(continent=="South America") %>% 
  group_by(country) %>%
  summarise(Species_Lost=n()) %>% 
  arrange(desc(Species_Lost))

SouthAmP %>% 
  kable()

ggplot(SouthAmP, aes(forcats::fct_reorder(country,Species_Lost,.desc = TRUE),
                    Species_Lost),
       )+
  geom_col(fill="steelblue", alpha=0.8)+
  geom_text(aes(label=Species_Lost,vjust=-0.25), color="grey30")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        plot.title = element_text(hjust = 0.5, size = 20)) +
  labs(title = "Species lost by country",
       subtitle = "South America data",
       x="",y="")+
theme_bw()
```

